executable  = /afs/cern.ch/work/v/vveckaln/private/CMSSW_8_0_26_patch1/src/TopLJets2015/TopAnalysis/condor/mergeOutputs/FARM/$(cfgFile).sh
output      = /afs/cern.ch/work/v/vveckaln/private/CMSSW_8_0_26_patch1/src/TopLJets2015/TopAnalysis/condor/mergeOutputs/CONDOROUT/$(cfgFile).out
error       = /afs/cern.ch/work/v/vveckaln/private/CMSSW_8_0_26_patch1/src/TopLJets2015/TopAnalysis/condor/mergeOutputs/CONDOROUT/$(cfgFile).err
log         = /afs/cern.ch/work/v/vveckaln/private/CMSSW_8_0_26_patch1/src/TopLJets2015/TopAnalysis/condor/mergeOutputs/FARM/*.$(ClusterId).log
arguments   = $(ClusterId) $(ProcId)
+JobFlavour = "longlunch"
cfgFile=MC13TeV_TTJets_herwig_jec_FlavorPureBottom_down
queue 1
cfgFile=MC13TeV_TTJets_herwig_jec_CorrelationGroupMPFInSitu_up
queue 1
cfgFile=MC13TeV_TTJets_herwig_jer_up
queue 1
cfgFile=MC13TeV_TTJets_herwig_jec_FlavorPureGluon_up
queue 1
cfgFile=MC13TeV_TTJets_herwig_tracking_down
queue 1
cfgFile=MC13TeV_TTJets_herwig_btag_heavy_down
queue 1
cfgFile=MC13TeV_TTJets_herwig_jec_FlavorPureGluon_down
queue 1
cfgFile=MC13TeV_TTJets_herwig_jec_FlavorPureCharm_down
queue 1
cfgFile=MC13TeV_TTJets_herwig_csv_light_down
queue 1
cfgFile=MC13TeV_TTJets_herwig_btag_light_up
queue 1
cfgFile=MC13TeV_TTJets_herwig_jec_CorrelationGroupUncorrelated_down
queue 1
cfgFile=MC13TeV_TTJets_herwig_jec_FlavorPureCharm_up
queue 1
cfgFile=MC13TeV_TTJets_herwig_btag_heavy_up
queue 1
cfgFile=MC13TeV_TTJets_herwig_jec_RelativeFSR_down
queue 1
cfgFile=MC13TeV_TTJets_herwig_jec_CorrelationGroupMPFInSitu_down
queue 1
cfgFile=MC13TeV_TTJets_herwig_jec_FlavorPureQuark_down
queue 1
cfgFile=MC13TeV_TTJets_herwig_jec_FlavorPureQuark_up
queue 1
cfgFile=MC13TeV_TTJets_herwig_btag_light_down
queue 1
cfgFile=MC13TeV_TTJets_herwig_jer_down
queue 1
cfgFile=MC13TeV_TTJets_herwig_jec_CorrelationGroupUncorrelated_up
queue 1
cfgFile=MC13TeV_TTJets_herwig_jec_RelativeFSR_up
queue 1
cfgFile=MC13TeV_TTJets_herwig_csv_heavy_up
queue 1
cfgFile=MC13TeV_TTJets_herwig_csv_light_up
queue 1
cfgFile=MC13TeV_TTJets_herwig_csv_heavy_down
queue 1
cfgFile=MC13TeV_TTJets_herwig_tracking_up
queue 1
cfgFile=MC13TeV_TTJets_herwig_jec_FlavorPureBottom_up
queue 1
